apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: backstage
type: Opaque
data:
  POSTGRES_USER: YmFja3N0YWdl          # echo -n "backstage" | base64
  POSTGRES_PASSWORD: cGFzc3dvcmQ=      # echo -n "password" | base64
