apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-storage-claim
  namespace: backstage
spec:
  storageClassName: expandable-local   # ajuste para seu cluster
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
