apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-nodeport
spec:
  selector: # seletor para identificar os pods/deployment que esse svc irá expor
    app: nginx
  type: NodePort
  ports:
    - nodePort: 30085
      port: 80
      protocol: TCP
      targetPort: 80